on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node.version}}
          cache: 'npm'
          -run: |
             npm ci
             npm run build
             
        
  #     - name: npm install, build and test           
  #       run: |
  #         npm install
  #         npm run build
  # deploy:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  # #   - name: Checkout
  # #     uses: actions/checkout@master

  #   - name: deploy
  #     uses: appleboy/scp-action@master
  #     env:
  #       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  #       BUILD_DIR: test/build/ # The folder, the action should deploy.
  #       BUILD_SCRIPT: npm install && npm run-script build # The build script the action should run prior to deploying.
