on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: npm install, build and test
        run: |
          npm install
          npm run build
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
